export const brandWebsites = {
  airbnb: 'https://www.airbnb.com',
  apple: 'https://www.apple.com',
  figma: 'https://www.figma.com',
  cursor: 'https://www.cursor.com',
  elevenlabs: 'https://elevenlabs.io',
  linear: 'https://linear.app',
  nike: 'https://www.nike.com',
  airtable: 'https://www.airtable.com',
  'binance-us': 'https://www.binance.us',
  bmw: 'https://www.bmw.com',
  'cal-com': 'https://cal.com',
  'claude-anthropic': 'https://www.anthropic.com/claude',
  clay: 'https://www.clay.com',
  clickhouse: 'https://clickhouse.com',
  cohere: 'https://cohere.com',
  coinbase: 'https://www.coinbase.com',
  expo: 'https://expo.dev',
  ferrari: 'https://www.ferrari.com',
  framer: 'https://www.framer.com',
  hashicorp: 'https://www.hashicorp.com',
  ibm: 'https://www.ibm.com',
  intercom: 'https://www.intercom.com',
  kraken: 'https://www.kraken.com',
  lamborghini: 'https://www.lamborghini.com',
  lovable: 'https://lovable.dev',
  'meta-store': 'https://www.meta.com',
  minimax: 'https://www.minimax.io/en',
  mintlify: 'https://mintlify.com',
  miro: 'https://miro.com',
  'mistral-ai': 'https://mistral.ai',
  mongodb: 'https://www.mongodb.com',
  notion: 'https://www.notion.so',
  nvidia: 'https://www.nvidia.com',
  ollama: 'https://ollama.com',
  opencode: 'https://opencode.ai',
  pinterest: 'https://www.pinterest.com',
  posthog: 'https://posthog.com',
  raycast: 'https://www.raycast.com',
  renault: 'https://www.renault.com',
  replicate: 'https://replicate.com',
  resend: 'https://resend.com',
  revolut: 'https://www.revolut.com',
  runway: 'https://runwayml.com',
  sanity: 'https://www.sanity.io',
  sentry: 'https://sentry.io',
  shopify: 'https://www.shopify.com',
  spacex: 'https://www.spacex.com',
  spotify: 'https://www.spotify.com',
  stripe: 'https://stripe.com',
  supabase: 'https://supabase.com',
  superhuman: 'https://superhuman.com',
  tesla: 'https://www.tesla.com',
  'together-ai': 'https://www.together.ai',
  uber: 'https://www.uber.com',
  vercel: 'https://vercel.com',
  voltagent: 'https://voltagent.dev',
  warp: 'https://warp.dev',
  webflow: 'https://webflow.com',
  wise: 'https://wise.com',
  xai: 'https://x.ai',
  zapier: 'https://zapier.com',
};

export function getBrandWebsite(brand) {
  if (!brand) return '';
  return brandWebsites[brand.id] || '';
}
